from __future__ import annotations

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import QFrame, QHBoxLayout, QLabel, QPushButton, QVBoxLayout, QWidget


class NewGameMenu(QWidget):
    calculated_areas_requested = Signal()
    candidate_vote_requested = Signal()
    hex_memory_requested = Signal()
    monstruos_requested = Signal()
    back_requested = Signal()

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        outer = QVBoxLayout(self)
        outer.setContentsMargins(70, 50, 70, 50)
        outer.setSpacing(20)

        title = QLabel("Nueva partida")
        title.setObjectName("pageTitle")
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)

        game_card = QFrame()
        game_card.setObjectName("gameCard")
        card_layout = QHBoxLayout(game_card)
        card_layout.setContentsMargins(24, 24, 24, 24)
        card_layout.setSpacing(24)

        symbol = QLabel("●  ■  ▲")
        symbol.setObjectName("gameSymbol")
        symbol.setAlignment(Qt.AlignmentFlag.AlignCenter)

        text_layout = QVBoxLayout()
        name = QLabel("Áreas Calculadas")
        name.setObjectName("gameName")
        description = QLabel(
            "Juego de roles ocultos en el que los jugadores modifican e intercambian "
            "las puntuaciones de tres áreas."
        )
        description.setWordWrap(True)
        description.setObjectName("subtitle")
        play_button = QPushButton("Crear partida")
        play_button.clicked.connect(self.calculated_areas_requested)

        text_layout.addWidget(name)
        text_layout.addWidget(description)
        text_layout.addSpacing(8)
        text_layout.addWidget(play_button)

        card_layout.addWidget(symbol, 1)
        card_layout.addLayout(text_layout, 3)

        vote_card = QFrame()
        vote_card.setObjectName("gameCard")
        vote_layout = QHBoxLayout(vote_card)
        vote_layout.setContentsMargins(24, 24, 24, 24)
        vote_layout.setSpacing(24)
        vote_symbol = QLabel("☑  ◉  ☑")
        vote_symbol.setObjectName("gameSymbol")
        vote_symbol.setAlignment(Qt.AlignmentFlag.AlignCenter)
        vote_text = QVBoxLayout()
        vote_name = QLabel("Votación de candidatos")
        vote_name.setObjectName("gameName")
        vote_description = QLabel(
            "Crea una lista de candidatos y recibe votos desde móviles mediante un QR."
        )
        vote_description.setWordWrap(True)
        vote_description.setObjectName("subtitle")
        vote_button = QPushButton("Crear partida")
        vote_button.clicked.connect(self.candidate_vote_requested)
        vote_text.addWidget(vote_name)
        vote_text.addWidget(vote_description)
        vote_text.addSpacing(8)
        vote_text.addWidget(vote_button)
        vote_layout.addWidget(vote_symbol, 1)
        vote_layout.addLayout(vote_text, 3)

        hex_card = QFrame()
        hex_layout = QHBoxLayout(hex_card)
        hex_layout.setContentsMargins(24, 24, 24, 24)
        hex_layout.setSpacing(24)
        hex_symbol = QLabel("⬡  A  B  C")
        hex_symbol.setObjectName("gameSymbol")
        hex_symbol.setAlignment(Qt.AlignmentFlag.AlignCenter)
        hex_text = QVBoxLayout()
        hex_name = QLabel("Memoria hexagonal")
        hex_name.setObjectName("gameName")
        hex_description = QLabel("Memoriza un tablero de hexágonos y encuentra tres números alineados que sumen el objetivo.")
        hex_description.setWordWrap(True)
        hex_description.setObjectName("subtitle")
        hex_button = QPushButton("Crear partida")
        hex_button.clicked.connect(self.hex_memory_requested)
        hex_text.addWidget(hex_name)
        hex_text.addWidget(hex_description)
        hex_text.addSpacing(8)
        hex_text.addWidget(hex_button)
        hex_layout.addWidget(hex_symbol, 1)
        hex_layout.addLayout(hex_text, 3)

        back_button = QPushButton("Volver")
        back_button.setObjectName("secondaryButton")
        back_button.clicked.connect(self.back_requested)

        outer.addWidget(title)
        outer.addSpacing(20)
        outer.addWidget(game_card)
        outer.addWidget(vote_card)
        outer.addWidget(hex_card)
        monsters_card = QFrame()
        monsters_card.setObjectName("gameCard")
        monsters_layout = QHBoxLayout(monsters_card)
        monsters_layout.setContentsMargins(24, 24, 24, 24)
        monsters_symbol = QLabel("🎃  👻  🕷️")
        monsters_symbol.setObjectName("gameSymbol")
        monsters_symbol.setAlignment(Qt.AlignmentFlag.AlignCenter)
        monsters_text = QVBoxLayout()
        monsters_name = QLabel("Monstruos de Halloween")
        monsters_name.setObjectName("gameName")
        monsters_description = QLabel("Combate monstruos por turnos, consigue recompensas y decide quién da el golpe final.")
        monsters_description.setWordWrap(True)
        monsters_description.setObjectName("subtitle")
        monsters_button = QPushButton("Crear partida")
        monsters_button.clicked.connect(self.monstruos_requested)
        monsters_text.addWidget(monsters_name)
        monsters_text.addWidget(monsters_description)
        monsters_text.addWidget(monsters_button)
        monsters_layout.addWidget(monsters_symbol, 1)
        monsters_layout.addLayout(monsters_text, 3)
        outer.addWidget(monsters_card)
        outer.addStretch()
        outer.addWidget(back_button)
